WHW13/part_2/quote/noteapp/urls.py
from django.urls import path
from . import views

app_name = 'noteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('detail/<int:note_id>', views.detail, name='detail'),
]

WHW13/part_2/quote/notes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('noteapp.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

WHW13/part_2/quote/noteapp/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=25, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    name = models.CharField(max_length=50, null=False)
    description = models.CharField(max_length=150, null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Author)

    def __str__(self):
        return f"{self.name}"

WHW13/part_2/quote/noteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Author
from .models import Quote


class AuthorForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Author
        fields = ['name']

class QuoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['name', 'description']
        exclude = ['author']

WHW13/part_2/quote/noteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AuthorForm, QuoteForm
from .models import Author
from .models import Quote


# Create your views here.
def main(request):
    return render(request, 'noteapp/index.html')

def tag(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/author.html', {'form': form})

    return render(request, 'noteapp/author.html', {'form': AuthorForm()})


def quote(request):
    author = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_author = Author.objects.filter(name__in=request.POST.getlist('author'))
            for author in choice_author.iterator():
                new_quote.author.add(author)

            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/quote.html', {"author": author, 'form': form})

    return render(request, 'noteapp/quote.html', {"author": author, 'form': QuoteForm()})
...

def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'noteapp/detail.html', {"quote": quote})

WHW13/part_2/quote/noteapp/templates/detail.html
{% extends "noteapp/base.html" %}

{% block content %}
<h2>{{note.name}}</h2>
<h3>{{note.description}}</h3>
<h4>{{note.done}}</h4>
<h5>{{note.created}}</h5>
{% for tag in note.tags.all%}
<h6>{{tag.name}}</h6>
{% endfor %}

{% endblock %}

WHW13/part_2/quote/noteapp/templates/noteapp/author.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

WHW13/part_2/quote/noteapp/templates/noteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

WHW13/part_2/quote/noteapp/templates/noteapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
</head>

<body>
    <main class="container">
        <h1>Main page</h1>
    </main>
</body>

</html>

WHW13/part_2/quote/noteapp/templates/noteapp/quote.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" multiple="multiple" required>
                {% for author in authors %}
                <option value="{{author.name}}">{{author.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}
